### PR TITLE
Added folder icon

### PR DESCRIPTION
**Pull request by DaniellMesquita**
Signed-off-by: Daniell Mesquita <daniellplasmmer@gmail.com>

### CODE REVIEW

**Comment by HelloZeroNet** [comment]
Thanks, but I think it's too platform specific and not necessary. You can create shortcuts to sites you want to have easily accessible, but for me filtering to 1Hello works well.

**Comment by DaniellMesquita** [comment]
It is not platform specific, because other OS can also show folder icons

**Comment by DaniellMesquita** [comment]
In this case, I implemented it just for Windows.
If you want to reopen this pull request, I can upload Linux and MacOS icons.

**Comment by HelloZeroNet** [comment]
Thanks, but I think it has no added value for regular users

**Comment by DaniellMesquita** [comment]
It adds value, because it makes ZeroHello into another site with icon, that makes it instant to find on Explorer.
On other sites I have, I added icons

**Comment by HelloZeroNet** [comment]
Why would anyone wants to find the ZeroHello folder other than it's developer?

**Pull request closed without merging**
